# Generated by Django 6.0.6 on 2026-06-18 00:46

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords e.g. hope, loss, time, identity', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
